services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: DB_CLIENT_DEBUG
        value: false
      - key: LOG_LEVEL
        value: info
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-thunder
          property: connectionString
      - fromGroup: babystory-production
  - type: redis
    name: redis-thunder
    region: oregon
    plan: starter # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru)
    ipAllowList: []
databases:
  - name: strapi
