services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_ENV
        fromGourp: babystory-production
      - key: CLOUDINARY_NAME
        fromGourp: babystory-production
        sync: false
      - key: CLOUDINARY_KEY
        fromGourp: babystory-production
        sync: false
      - key: CLOUDINARY_SECRET
        fromGourp: babystory-production
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        fromGroup: babystory-production
        generateValue: false
      - key: ADMIN_JWT_SECRET
        fromGroup: babystory-production
        generateValue: false
      - key: APP_KEYS
        fromGroup: babystory-production
        generateValue: true
      - key: DB_CLIENT_DEBUG
        value: false
      - key: LOG_LEVEL
        value: info
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-thunder
          property: connectionString
  - type: redis
    name: redis-thunder
    region: oregon
    plan: starter # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru
    ipAllowList: []
databases:
  - name: strapi
    plan: starter
