services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: false
      - key: ADMIN_JWT_SECRET
        generateValue: false
      - key: APP_KEYS
        generateValue: true
      - key: DB_CLIENT_DEBUG
        value: false
      - key: LOG_LEVEL
        value: info
  - type: redis
    name: redis-thunder
    region: oregon
    plan: starter # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru
    ipAllowList: []
databases:
  - name: strapi
    plan: starter
